markdown:       kramdown
kramdown:
  auto_ids:     true
encoding:       UTF-8
exclude:
  - .git/
  - package.json
  - package-lock.json
  - node_modules
sass:
  sass_dir: ./
  style: compressed

theme: default-haikalfikri-cdn-theme

plugins:
  - cdn-seo-tag

title: "👋 Haikal Fikri CDN Web Page"
description: "Default Web Page CDN Server"

twitter:
  username: haikalfiikrii

author:
  name: Haikal Fikri
  twitter: haikalfiikrii
